### ISSUE TITLE
List privacy settings are sent in all-caps instead of lowercase

### ISSUE THREAD

**Issue by jkraybill** [UweTrottmann/trakt-java#114]
Because of the ListPrivacy enum names (e.g. PUBLIC), the "privacy" value for List Creation (e.g. trakt.users().createList()) gets sent to Trakt as `privacy: "PUBLIC"` instead of `privacy: "public"`. Trakt ignores this, so all lists created are set to default (private).

This is an annoying one because you can't name an enum value "public" for obvious reasons.

I fixed this in my local by removing ListPrivacy altogether and just using a String for privacy values, but I'm not sure that's the ideal fix.

**Comment by UweTrottmann** [comment]
Thanks for reporting. IIRC only `toString()` needs to be overridden and Gson will use that value.

**Comment by UweTrottmann** [comment]
Actually it is already. Possibly something has changed here. Investigate.
https://github.com/UweTrottmann/trakt-java/blob/master/src/main/java/com/uwetrottmann/trakt5/enums/ListPrivacy.java

**Comment by jkraybill** [comment]
My code looks like that, but it was definitely sending all caps, not sure why.

**Comment by mlaggner** [comment]
Just discovered the same. Maybe the fix https://github.com/dimwael/gson/pull/2/commits/ea4730eb89ddc141c8ea378a43f6e9e99a3cf227 changed the behaviour?

maybe using 
```
@SerializedName("public")
PUBLIC
```

would be an alternative? (instead of using something like the workarounds with toString / STRING_MAPPING which achieves the same)

**Comment by mlaggner** [comment]
just found out, that the serializer for the enum ListPrivacy has not been registered with gson:
https://github.com/UweTrottmann/trakt-java/blob/master/src/main/java/com/uwetrottmann/trakt5/TraktV2Helper.java#L32

but there is still the question if it is not better to work with the GSON annotation?

**Comment by UweTrottmann** [comment]
OK, confirmed. I think I must have confused retrofit using `.toString()` vs gson using the enum name. Will be fixed with the next update.
