### ISSUE TITLE
No method for removing playback

### ISSUE THREAD

**Issue by KarkaLT** [UweTrottmann/trakt-java#126]
Hello, I've noticed that there is not method for removing playbacks. [This is the method I'm talking about.](https://trakt.docs.apiary.io/#reference/sync/remove-playback/remove-a-playback-item)

**Comment by UweTrottmann** [comment]
Thanks. Feel free to [submit a pull request](https://github.com/UweTrottmann/trakt-java/blob/main/CONTRIBUTING.md) to add it.
