### ISSUE TITLE
Unsupported class file major version 63

### ISSUE THREAD

**Issue by Goooler** [UweTrottmann/trakt-java#129]
Build [tivi](https://github.com/chrisbanes/tivi) with Java 19:

```
> Transform trakt.jar (project :api:trakt) with DexingWithClasspathTransform
AGPBI: {"kind":"error","text":"java.lang.IllegalArgumentException: Unsupported class file major version 63","sources":[{"file":"/Users/goooler/StudioProjects/tivi/api/trakt/build/libs/trakt.jar"}],"tool":"D8"}

> Transform tmdb.jar (project :api:tmdb) with DexingWithClasspathTransform
AGPBI: {"kind":"error","text":"java.lang.IllegalArgumentException: Unsupported class file major version 63","sources":[{"file":"/Users/goooler/StudioProjects/tivi/api/tmdb/build/libs/tmdb.jar"}],"tool":"D8"}
```

**Comment by Goooler** [comment]
Hmmm, just wait for the Gradle 7.6 release and try again, it might be fixed.

**Comment by UweTrottmann** [comment]
Thanks. But I don't quite follow how this is an issue of this library. This indicates that whatever this project is compiling there is using a byte code version not supported by the tooling, no? This libraries artifacts are Java 8 byte code to remain compatible with Android, but should be forward compatible?

**Comment by Goooler** [comment]
Yes, it might be something incompatible with AGP or Gradle, I'll recheck after their new releases.
