### ISSUE TITLE
Using Client ID as API Key return error 403

### ISSUE THREAD

**Issue by SkidrowDev01** [UweTrottmann/trakt-java#47]
I don't know how to get correct login information becasue using client id as api key return error 403.
What could be? Maybe an internal trakt error?
Thank you

**Comment by UweTrottmann** [comment]
Has your app been approved, yet? You should join the trakt API Google+
community.

**Comment by SkidrowDev01** [comment]
Well no I didn't make a request approval. I thought it would be used only for extra permissions.

**Comment by UweTrottmann** [comment]
It needs to be approved in any case. For testing you can work around this
by always supplying an OAuth access token from the account you registered
the app with.

**Comment by SkidrowDev01** [comment]
OAuth access token is equals to Client secret?

**Comment by UweTrottmann** [comment]
Nope. You might want to have a look at e.g.
https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2.

**Comment by SkidrowDev01** [comment]
Ok I tried to get an access token via TrackV2.getAccessToken but I run in <code>OAuthProblemException{error='unsupported_response_type', description='Invalid response! Response body is not application/json encoded', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}</code>
The OAuth authorization code has been created with this callback uri : urn:ietf:wg:oauth:2.0:oob
Trakt suggests it for local test.
Sorry to make you lose your time

**Comment by UweTrottmann** [comment]
As the exception says, trakt is returning an invalid response. You might want to try with `http://localhost` for the callback URI. You can also look at `AuthTest` test cases in `src/test`.

**Comment by SkidrowDev01** [comment]
Ok got it.
Thanks, now all working well.
