### ISSUE TITLE
Support Users > Watchlist

### ISSUE THREAD

**Issue by 0rangeX** [UweTrottmann/trakt-java#60]
I am missing the possibility how to get a users watchlisted movies.
Any hints how to do that?

Thank you.

**Comment by UweTrottmann** [comment]
For the authenticated user there is [this Sync method](https://github.com/UweTrottmann/trakt-java/blob/v4.3.1/src/main/java/com/uwetrottmann/trakt/v2/services/Sync.java#L216).

But the watchlist method for any user has not been implemented, yet!
