### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by athornz** [UweTrottmann/trakt-java#61]
Any reason why this built using maven and not gradle? If I were to convert this to gradle would you merge?

**Comment by UweTrottmann** [comment]
Any reason why this should be built with Gradle instead of Maven? ;) So far
it's easier to publish through Sonatype with Maven.

**Comment by athornz** [comment]
Haha ok fair enough. I'd like to add support for RxJava. What's your thoughts on that?

**Comment by florianmski** [comment]
@athornz In which way? Duplicating all the methods and using the retrofit built-in support for Observable?
In Traktoid I just wrap the trakt calls in a [TraktObservable](https://github.com/florianmski/Traktoid/blob/master/app/src/main/java/com/florianmski/tracktoid/rx/observables/TraktObservable.java)

**Comment by athornz** [comment]
Yea, duplicating the methods to save me wrapping each api call :)

**Comment by UweTrottmann** [comment]
In this case I guess it's better to create your own library?
