### ISSUE TITLE
List of episodes method missing

### ISSUE THREAD

**Issue by adammw** [UweTrottmann/trakt-java#73]
There doesn't appear to be any methods to retrieve a list of episodes for a given season, ie.
make a call like /shows/19792/seasons/1/episodes and return a list of Episode entity objects.

**Comment by adammw** [comment]
I was expecting this under trakt.episodes().episodes() or something but it looks like it might already be available under trakt.seasons().season()

**Comment by UweTrottmann** [comment]
http://docs.trakt.apiary.io is your friend ;) The library is structured
according to it.

Uwe

Sent from my phone.
Am 07.11.2015 07:32 schrieb "Adam Malcontenti-Wilson" <
notifications@github.com>:
