### ISSUE TITLE
Movie/Show/Episode Stats

### ISSUE THREAD

**Issue by robertmallare** [UweTrottmann/trakt-java#78]
Hi,

Does the wrapper now has support for querying media "Stats"? Url below.

https://api.trakt.tv/movies/id/stats

**Comment by UweTrottmann** [comment]
You mean http://docs.trakt.apiary.io/#reference/movies/stats/get-movie-stats? It did not.

But I just added support which will ship with 5.1.0.

**Comment by robertmallare** [comment]
Wow! Cool! When will you release 5.1.0?

**Comment by UweTrottmann** [comment]
[Already did](https://github.com/UweTrottmann/trakt-java/blob/master/CHANGELOG.md). Should be on Maven Central in the next few hours.

**Comment by robertmallare** [comment]
Cool! Thanks man! :)
